### PR TITLE
84 password protection

### PR DESCRIPTION
**Pull request by matt-auckland**

### CODE REVIEW

**Comment by craigmacgregor** [comment]
Can't review until the bugs are fixed and an order can be placed.

**Comment by matt-auckland** [comment]
Orders can be placed now

**Comment by craigmacgregor** [comment]
I seem to be getting some errors on start up of this branch. Not entirely sure if its just this branch. Will test. The server does appear to proceed past this error and start.

```
Craigs-MacBook-Pro:polymorph craigmacgregor$ npm run express

Polymorph@0.0.0 express /Users/craigmacgregor/Projects/polymorph
node server.js

MongoDB connection error: { Error: Trying to open unclosed connection.
    at NativeConnection.Connection._handleOpenArgs (/Users/craigmacgregor/Projects/polymorph/node_modules/mongoose/lib/connection.js:213:11)
    at NativeConnection.<anonymous> (/Users/craigmacgregor/Projects/polymorph/node_modules/mongoose/lib/connection.js:308:37)
    at NativeConnection.deprecated [as open] (internal/util.js:52:15)
    at Mongoose.connect (/Users/craigmacgregor/Projects/polymorph/node_modules/mongoose/lib/index.js:268:47)
    at Object.<anonymous> (/Users/craigmacgregor/Projects/polymorph/server/lib/db/blackList.model.js:6:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/craigmacgregor/Projects/polymorph/server/lib/db/login.ctrl.js:5:24)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/craigmacgregor/Projects/polymorph/server/lib/order/status.ctrl.js:2:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/craigmacgregor/Projects/polymorph/server/routes/api.js:9:25)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/craigmacgregor/Projects/polymorph/server.js:9:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3 state: 2 }
MongoDB connection error: { Error: Trying to open unclosed connection.
    at NativeConnection.Connection._handleOpenArgs (/Users/craigmacgregor/Projects/polymorph/node_modules/mongoose/lib/connection.js:213:11)
    at NativeConnection.<anonymous> (/Users/craigmacgregor/Projects/polymorph/node_modules/mongoose/lib/connection.js:308:37)
    at NativeConnection.deprecated [as open] (internal/util.js:52:15)
    at Mongoose.connect (/Users/craigmacgregor/Projects/polymorph/node_modules/mongoose/lib/index.js:268:47)
    at Object.<anonymous> (/Users/craigmacgregor/Projects/polymorph/server/lib/db/failedLogins.model.js:6:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/craigmacgregor/Projects/polymorph/server/lib/db/login.ctrl.js:6:27)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/craigmacgregor/Projects/polymorph/server/lib/order/status.ctrl.js:2:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/craigmacgregor/Projects/polymorph/server/routes/api.js:9:25)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/craigmacgregor/Projects/polymorph/server.js:9:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3 state: 2 }
MongoDB connection error: { Error: Trying to open unclosed connection.
    at NativeConnection.Connection._handleOpenArgs (/Users/craigmacgregor/Projects/polymorph/node_modules/mongoose/lib/connection.js:213:11)
    at NativeConnection.<anonymous> (/Users/craigmacgregor/Projects/polymorph/node_modules/mongoose/lib/connection.js:308:37)
    at NativeConnection.deprecated [as open] (internal/util.js:52:15)
    at Mongoose.connect (/Users/craigmacgregor/Projects/polymorph/node_modules/mongoose/lib/index.js:268:47)
    at Object.<anonymous> (/Users/craigmacgregor/Projects/polymorph/server/lib/db/failedLogins.model.js:6:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/craigmacgregor/Projects/polymorph/server/lib/db/login.ctrl.js:6:27)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/craigmacgregor/Projects/polymorph/server/lib/order/status.ctrl.js:2:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/craigmacgregor/Projects/polymorph/server/routes/api.js:9:25)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/craigmacgregor/Projects/polymorph/server.js:9:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3 state: 2 }
(node:1558) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
(node:1558) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Trying to open unclosed connection.
(node:1558) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1558) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Trying to open unclosed connection.

Date: Wed Aug 30 2017 16:42:33 GMT+1200 (NZST)
Error Code: n/a
Error Message: API running on https://localhost:3000

-----------------------------------------------------------


Date: Wed Aug 30 2017 16:42:33 GMT+1200 (NZST)
Error Code: n/a
Error Message: Sending start up notification email.

-----------------------------------------------------------


Date: Wed Aug 30 2017 16:42:33 GMT+1200 (NZST)
Error Code: Server Start Up
Error Message: Start Up Complete @2017-08-30T04:42:33.601Z, Polymorph Version: 0.0.1

-----------------------------------------------------------

nodemail success: 250 2.0.0 OK 1504068158 g20sm6810184pfg.138 - gsmtp
```

**Comment by craigmacgregor** [comment]
IP address being recorded as ::1 in the database, doesn't seem like that's right?

screen shot 2017-08-30 at 5 24 11 pm

**Comment by matt-auckland** [comment]
Might be a localhost thing, will look into it tomorrow

**Pull request merged**
